# Generated by Django 2.2.7 on 2020-11-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=200)),
                ('id_telegram_owner', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog', models.CharField(choices=[('idle', 'бот свободен'), ('e_q', 'бот ждет цитату'), ('say', 'бот ждет фидбек')], default='idle', max_length=4)),
                ('nick_id', models.BigIntegerField(default=0)),
                ('nick_name', models.CharField(max_length=200)),
                ('sent_message', models.DateTimeField(auto_now_add=True)),
                ('next_message', models.DateTimeField(auto_now_add=True)),
                ('need_link', models.BooleanField(default=False)),
                ('user_min', models.IntegerField(default=420)),
                ('user_max', models.IntegerField(default=720)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'ОК'), ('NEW', 'Новое'), ('ED', 'Отредактировано')], default='NEW', max_length=3)),
                ('quote', models.TextField()),
                ('link', models.TextField()),
                ('nick_id', models.BigIntegerField(default=0)),
                ('code', models.CharField(default='jVomefYlXL', max_length=10)),
            ],
        ),
    ]
