# Generated by Django 2.2.7 on 2020-11-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smileup', '0002_auto_20201104_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='dialog',
            field=models.CharField(choices=[('idle', 'бот свободен'), ('e_q', 'бот ждет цитату'), ('say', 'бот ждет фидбек'), ('stop', 'бот выключен')], default='idle', max_length=4),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='need_link',
            field=models.BooleanField(default=True),
        ),
    ]
